server:
  port: 8080
  servlet:
    context-path: /Shopme

spring:
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/shopmedb
    username: root

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false

